### ISSUE TITLE
Using postMessage with figma-jsonrpc results in error 

### ISSUE THREAD

**Issue by oisinlavery** [Lona/figma-jsonrpc#1]
I get an error when I try to also use postMessage to communicate between the UI and Figma.

Sent from UI:
`window.parent.postMessage({ pluginMessage: { type: "get-active" } }, "*")`

Error:
![Screen Shot 2020-02-25 at 3 48 02 PM](https://user-images.githubusercontent.com/1757344/75263928-8abda380-57e6-11ea-8007-4def3d13a49c.png)

**Comment by mathieudutour** [comment]
why do you use postMessage in addition to figma-jsonrpc?

**Comment by oisinlavery** [comment]
I couldn't figure out a way to pipe **selectionchange** and **currentpagechange** to the UI side using figma-jsonrpc. 

Maybe I'm just missing something obvious?

```javascript
figma.on("selectionchange", () => { 
  figma.ui.postMessage({
    type: "selection-change",
    selection: figma.currentPage.selection,
  })
})
```

**Comment by mathieudutour** [comment]
add a method in your api:
  ```ts
  import rpc from "figma-jsonrpc";

  export const api = rpc({
    selectionChange(selection) {
      // this will be executed on the UI side
    },
  });
  ```

  ```ts
  import { api } from "./api";

  figma.on("selectionchange", () => { 
    api.selectionChange(figma.currentPage.selection)
  })
  ```

**Comment by oisinlavery** [comment]
What does the UI side code look like in this case?

**Comment by mathieudutour** [comment]
well I don't know, what do you want it to do? haha

you at least need to import the api so that it's setup

**Comment by oisinlavery** [comment]
Your code shows how to setup this on plugin side, but I am not sure how to hook this up on the UI side...

// UI

```javascript
import { api } from "../plugin/api"
api.selectionChange.then(selection => {...})
```

```javascript
import { api } from "../plugin/api"
api.selectionChange((selection) => { ... })
```

etc.

**Comment by mathieudutour** [comment]
you just implement the api?

```js
import rpc from "figma-jsonrpc";

export const api = rpc({
  selectionChange(selection) {
    // this will be executed on the UI side
    do something with the selection
  },
});

```

**Comment by oisinlavery** [comment]
Maybe a more concrete example will help :)

I am trying to replace the listener in my React hook. How would the UI listen for changes happening in the sandbox?

```javascript
import { useEffect, useState } from "react"

export default function useSelection(): BaseNode[] {
  const [selection, setSelection] = useState([])

  useEffect(() => {
    window.addEventListener("message", (event: MessageEvent) => {
      const { type, selection } = event.data.pluginMessage
      if (type === "selection-change") {
        setSelection(selection)
      }
    })
  }, [])

  return selection
}

```

it's not a big deal if this can't be done. I'm happy to use postMessage to communicate from sandbox to UI, and figma-jsonrpc to communicate from ui to sandbox.

**Comment by mathieudutour** [comment]
right, so you can do something like:

in your react hook:
```js
import { useEffect, useState } from "react"

export default function useSelection(): BaseNode[] {
  const [selection, setSelection] = useState([])

  useEffect(() => {
    window._onSelectionChange = setSelection
    return () => { delete window._onSelectionChange }
  }, [])

  return selection
}
```

in the api:
```js
import rpc from "figma-jsonrpc";

export const api = rpc({
  selectionChange(selection) {
    if (typeof window._onSelectionChange !== 'undefined') {
      window._onSelectionChange(selection)
    }
  },
});
```

or create your own event emitter if you will use `useSelection` multiple times

**Comment by oisinlavery** [comment]
I had tried something like this but calling api methods from within `figma.on("selectionchange", () => {...})` returns the following error:

![Screen Shot 2020-02-27 at 10 42 52 AM](https://user-images.githubusercontent.com/1757344/75437332-f53d2380-594d-11ea-854d-25e1b2ce20d9.png)

**Comment by mathieudutour** [comment]
did you import the api?

**Comment by oisinlavery** [comment]
Yes. Typescript finds the methods fine

```javascript
import { api } from "./api"

figma.loadFontAsync({ family: "Roboto", style: "Regular" }).then(() => {
  figma.showUI(__html__, {
    width: 400,
    height: 600,
  })
})

figma.on("selectionchange", () => {
  console.log({ api })
  api.selectionChange(figma.currentPage.selection)
})
```

when I log api the methods are there too:

![Screen Shot 2020-02-27 at 11 57 30 AM](https://user-images.githubusercontent.com/1757344/75442989-6c77b500-5958-11ea-9f36-29040443f7af.png)


![Screen Shot 2020-02-27 at 11 55 44 AM](https://user-images.githubusercontent.com/1757344/75442841-2a4e7380-5958-11ea-8aa6-a89b2c329e9d.png)

**Comment by mathieudutour** [comment]
You also need to import it on the ui side so that the methods can be registered

**Comment by oisinlavery** [comment]
Yes I was importing it in the ui code.

I looked through your code and discovered **option.defineOnUI**
I've defined 2 separate api instances, one for ui, one for sandbox and that works:

```javascript
export const api = rpc({
  loadAuthTokens,
  saveAuthTokens,
  deleteAuthTokens,
  updateNodeData,
  selectPage,
  selectScreen,
  getImagesForSelection,
  getActive,
  refreshActive,
})

export const uiApi = rpc(
  {
    selectionChange(selection) {
      if (typeof (window as any)._onSelectionChange !== "undefined") {
        ;(window as any)._onSelectionChange(selection)
      }
    },
  },
  {
    defineOnUI: true,
  }
)
```

**Comment by mathieudutour** [comment]
oh right I forgot about that option. Gonna update the readme

**Comment by oisinlavery** [comment]
Great! Thanks again for your help.

**Comment by mathieudutour** [comment]
Actually I've been curious if we could improve the DX for react.

Could you try installing `figma-jsonrpc@0.4.0-pre0`?

Then you should be able to do:
in your plugin
```js
import 'figma-jsonrpc/hooks/useFigmaSelection' // to register the hook
```
in your UI
```js
import useFigmaSelection from 'figma-jsonrpc/hooks/useFigmaSelection'

const Component = () => {
  const selection = useFigmaSelection()
}
```

If it works we could create some hooks to cover most use cases

**Comment by oisinlavery** [comment]
Great idea, I'll try it out tomorrow.
