### ISSUE TITLE
Sending image data from ui to sandbox isn't working

### ISSUE THREAD

**Issue by oisinlavery** [Lona/figma-jsonrpc#4]
sending a UInt8Array changes the data (see screenshot). 

Regular postMessage doesn't do this.

![Screen Shot 2020-03-09 at 3 29 10 PM](https://user-images.githubusercontent.com/1757344/76229848-c14de200-621a-11ea-9cc0-8a9933d3ba26.png)

**Comment by oisinlavery** [comment]
I guess this is related to JSON.stringify and JSON.parse of the message.

Another side effect of this is that undefined values are removed, whereas PostMessage leaves them intact.

**Comment by mathieudutour** [comment]
right, the name of the library is `JSON-rpc` 😄

`UInt8Array` isn't part of JSON (same as undefined). But I guess we could make an exception because we control both side the rpc.

We might not have to stringify/parse

**Comment by oisinlavery** [comment]
That's a fair point 😜

I was able to reassemble the a UInt8Array on the other side although the Typescript typings said it was already a UInt8Array which caused the confusion.

![Screen Shot 2020-03-10 at 5 52 01 PM](https://user-images.githubusercontent.com/1757344/76343330-de0c1780-62f7-11ea-98a4-ce5d0eda899c.png)

**Comment by mathieudutour** [comment]
could you try v0.4.0-pre2? It should fix this

**Comment by oisinlavery** [comment]
Swapped in v0.4.0-pre2 and getting this error:

<img width="557" alt="Screen Shot 2020-03-17 at 12 25 37 PM" src="https://user-images.githubusercontent.com/1757344/76856111-7ea78d80-684a-11ea-920e-11e1eeb07b32.png">

**Comment by mathieudutour** [comment]
Ah my bad, 0.4.0-pre5 should work

**Comment by oisinlavery** [comment]
This is working well for me now, thanks for all the improvements.
