### ISSUE TITLE
Prefer figma.ui.on over figma.ui.onmessage

### ISSUE THREAD

**Issue by headwindz** [Lona/figma-jsonrpc#5]
Problem: If users use `figma-jsonrpc` and have locally defined `figma.ui.onmessage` logic, they will conflict and override as more than one `figma.ui.onmessage` can't coexist. [Source code here](https://github.com/Lona/figma-jsonrpc/blob/master/rpc.js#L7).

A better way to avoid this is to use [`figma.ui.on`](https://www.figma.com/plugin-docs/api/properties/figma-ui-on/) instead

**Comment by mathieudutour** [comment]
Happy to accept a PR to fix this

**Comment by headwindz** [comment]
> Happy to accept a PR to fix this

@mathieudutour  PR here :- https://github.com/Lona/figma-jsonrpc/pull/6 . Please help review
